apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hypershift
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mleonova-tenant/hypershift/hypershift@sha256:96194d010ff5bdf679db2615339f75a47e6ff72656fa876383ed338ac012ba48
        name: container-image
        resources: {}
status: {}
